version: "3"

services:
  holadocker:
    container_name: ci_holadocker
    image: analistasistema/hola-docker
    restart: always
    expose:
      - "80"
      - "443"
    volumes:
      - .:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=pedidoswebdev.iancarina.com.ve
      - LETSENCRYPT_HOST=pedidoswebdev.iancarina.com.ve
      - LETSENCRYPT_EMAIL=pedidosweb@iancarina.com.ve
    networks:
      - corporacionmarynet

networks:
  corporacionmarynet:
    external: true
