version: 2
jobs:   
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints: 
            - https://github.com/analistasistema/hola-docker/tree/circleci-project-setup/.circleci"48:90:a8:c9:54:14:c2:00:13:c0:9d:bf:92:71:87:eb"
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t analistasistema/hola-docker:$CIRCLE_SHA1 .
      - run: docker push analistasistema/hola-docker:$CIRCLE_SHA1
      - run: ssh -o StrictHostKeyChecking=no administrador@pedidosweb.iancarina.com.ve -p 8822 "sudo /bin/bash /root/docker/deploy.sh $CIRCLE_SHA1"
